python benchmark.py \
    --model=ResNet50 \
    --batch_size=128 \
    --dy2static=True \
    --static_op_fuse=False \
    --use_amp=True \
    --warmup_steps=30 \
    --run_steps=100 \
    --data_format="NCHW" \
    --use_scale=Fasle \
    --input_channels=3 \
    --amp_mode="O1"
